str=input("英文：")

My_dic={}

a=str.count("a")+str.count("A")
My_dic["A"] = a
b=str.count("b")+str.count("B")
My_dic["B"] = b
c=str.count("c")+str.count("C")
My_dic["C"] = c
d=str.count("d")+str.count("D")
My_dic["D"] = d
e=str.count("e")+str.count("E")
My_dic["E"] = e
f=str.count("f")+str.count("F")
My_dic["F"] = f
g=str.count("g")+str.count("G")
My_dic["G"] = g
h=str.count("h")+str.count("H")
My_dic["H"] = h
i=str.count("i")+str.count("I")
My_dic["I"] = i
j=str.count("j")+str.count("J")
My_dic["J"] = j
k=str.count("k")+str.count("K")
My_dic["K"] = k
l=str.count("l")+str.count("L")
My_dic["L"] = l
m=str.count("m")+str.count("M")
My_dic["M"] = m
n=str.count("n")+str.count("N")
My_dic["N"] = n
o=str.count("o")+str.count("O")
My_dic["O"] = o
p=str.count("p")+str.count("P")
My_dic["P"] = p
q=str.count("q")+str.count("Q")
My_dic["Q"] = q
r=str.count("r")+str.count("R")
My_dic["R"] = r
s=str.count("s")+str.count("S")
My_dic["S"] = s
t=str.count("t")+str.count("T")
My_dic["T"] = t
u=str.count("u")+str.count("U")
My_dic["U"] = u
v=str.count("v")+str.count("V")
My_dic["V"] = v
w=str.count("w")+str.count("W")
My_dic["W"] = w
x=str.count("x")+str.count("X")
My_dic["X"] = x
y=str.count("y")+str.count("Y")
My_dic["Y"] = y
z=str.count("z")+str.count("Z")
My_dic["Z"] = z

print(My_dic)
